#! /bin/sh

#--------------------------------------------
# 这是一个批量修改文件内容的脚本，书写的目的是为了改变文件内容的哈希值，主要用于“你懂的”领域，目前还没有想到别的应用场景。
# 递归代码参考 http://yejinxin.github.io/scripts-to-traverse-folder-recursively/

# 使用方法：(1)把脚本下载到本地
#         (2) chmod +x MagicShell
#         (3) 可以传入一个路径 ./MagicShell /Users/Downloads/testHashDirectory
#         (4) 可以传入多个路径 ./MagicShell /Users/Downloads/testHashDirectory1 ./MagicShell /Users/Downloads/testHashDirectory1
#         (5) 也可以传入单个文件  ./MagicShell   /Users/Downloads/testHash/file1.txt
#         (6) 也可以传入多个文件  ./MagicShell   /Users/Downloads/testHash/file1.txt /Users/Downloads/testHash/file2.txt
# 特色：批量修改内容，方便快捷。
#--------------------------------------------

function walk()
{
  for file in `ls $1`
  do
    local path=$1"/"$file
    if [ -d $path ]
     then
      echo "DIR $path"
      #如果是路径，则递归调用
      walk $path
    else
      echo "FILE $path"
      #如果是文件，则处理
      echo "A" >> $path
    fi
  done
}

function checkInput()
{
  if [ -d $1 ]
   then
    #如果传入的参数是一个路径
    echo "DIR $1"
    walk $1
  else
    #如果传入的参数是一个文件
    echo "FILE $1"
    echo "A" >> $1
  fi
}

#循环来遍历所有的参数
for args in $@
do
  checkInput $args
done
