#! /bin/sh

#--------------------------------------------
# 这是一个批量修改文件内容的脚本，书写的目的是为了改变文件内容的哈希值，主要用于“你懂的”领域，目前还没有想到别的应用场景。

# 使用方法：(1)把脚本下载到本地
#         (2) chmod +x MagicShell
#         (3) ./MagicShell /Users/Downloads/testHash
# 特色：批量修改内容，方便快捷。
#--------------------------------------------

function walk()
{
  for file in `ls $1`
  do
    local path=$1"/"$file
    if [ -d $path ]
     then
      echo "DIR $path"
      walk $path
    else
      echo "FILE $path"
      echo "A" >> $path
    fi
  done
}

if [ $# -ne 1 ]
then
  echo "USAGE: $0 TOP_DIR"
else
  walk $1
fi
